app/main/__init__.py
from flask import Blueprint, session

main = Blueprint('main', __name__)

from . import views


@main.before_request
def func():
    session.modified = True

app/main/views.py
"""
.. module:: main.views.

   :synopsis: Handles all core URL endpoints for the timeclock application
"""
from flask import (
    current_app,
    flash,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from flask_login import current_user

from app.constants import OPENRECORDS_DL_EMAIL
from app.constants.response_privacy import PRIVATE
from app.lib.db_utils import create_object, update_object
from app.lib.email_utils import send_contact_email
from app.models import Emails, Users
from app.request.forms import TechnicalSupportForm
from . import main


@main.route('/', methods=['GET', 'POST'])
def index():
    fresh_login = request.args.get('fresh_login', False)
    verify_mfa = request.args.get('verify_mfa', False)
    if current_user.is_authenticated:
        if verify_mfa:
            if current_user.has_mfa:
                return redirect(url_for('mfa.verify'))
            else:
                return redirect(url_for('mfa.register'))
        if fresh_login:
            if current_user.session_id is not None:
                return render_template('main/home.html', duplicate_session=True)
            update_object(
                {
                    'session_id': session.sid
                },
                Users,
                current_user.guid
            )
    return render_template('main/home.html')


@main.route('/index.html', methods=['GET'])
@main.route('/status', methods=['GET'])
def status():
    return '', 200


@main.route('/contact', methods=['GET', 'POST'])
@main.route('/technical-support', methods=['GET', 'POST'])
def technical_support():
    form = TechnicalSupportForm()

    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        subject = request.form.get('subject')
        message = request.form.get('message')

        if all((name, email, subject, message)):
            body = "Name: {}\n\nEmail: {}\n\nSubject: {}\n\nMessage:\n{}".format(
                name, email, subject, message)
            create_object(
                Emails(
                    request_id=None,
                    privacy=PRIVATE,
                    to=OPENRECORDS_DL_EMAIL,
                    cc=None,
                    bcc=None,
                    subject=subject,
                    body=body,
                )
            )
            if current_user.is_agency:
                send_contact_email(subject, [current_app.config['OPENRECORDS_AGENCY_SUPPORT_DL']], body, email)
            else:
                send_contact_email(subject, [OPENRECORDS_DL_EMAIL], body, email)
            flash('Your message has been sent. We will get back to you.', category='success')
        else:
            flash('Cannot send email.', category='danger')
    error_id = request.args.get('error_id', '')
    return render_template('main/contact.html', error_id=error_id, form=form)


@main.route('/faq', methods=['GET'])
def faq():
    return render_template('main/faq.html')


@main.route('/about', methods=['GET'])
def about():
    return render_template('main/about.html')


@main.route('/active', methods=['POST'])
def active():
    """
    Extends a user's session.
    :return:
    """
    session.modified = True
    return 'OK'

app/templates/main/about.html
{% extends "base.html" %}

{% block title %}About{% endblock %}

{% block custom_css %}
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='styles/about.css') }}"/>
{% endblock %}

{% block content %}
    <div class="row row-centered" role="main">
        <div class="col-sm-9 col-centered">
            <h1 id="about" class="text-center">
                About OpenRECORDS
            </h1>
            <br>
            <p class="lead">
                OpenRECORDS is a quick, simple way for you to submit a
                public records request to a New York City Agency.
            </p>
            <p>
                <strong>Most information on this site is public.</strong>
                Your contact information, and most personal information that may be contained
                in government documents will not be made available to the public.
            </p>
            <hr>
            <h2 class="about-heading" id="what">
                What is OpenRECORDS?
            </h2>
            <p>
                OpenRECORDS is a quick, simple way for individuals to submit Freedom of
                Information Law (FOIL) requests to a NYC agency. The web application also
                allows government employees to manage, respond to, and fulfill incoming requests.
                By providing more information about records requests, members of the public may
                find what they need without having to create a new public record request.
            </p>
            <hr>
            <h2 class="about-heading" id="documents">
                Why aren't all documents uploaded on OpenRECORDS?
            </h2>
            <p>
                City agencies will not publicly release records or information that violates your right to privacy.
                City agencies will not make records available that have been exempted from disclosure by Federal,
                State, or Local statute, including records that would impair contract awards or collective bargaining
                negotiations, are trade secrets, or are compiled for law enforcement purposes and if disclosed would
                interfere with investigations or judicial proceedings, deprive a person to a fair trial, identify a
                confidential source, reveal investigative techniques, or endanger a person's life. Records
                such as reports and data will be posted to the portal 20 business days after they are sent
                directly to the requester.
            </p>
            <hr>
            <h2 class="about-heading" id="why">
                History of OpenRECORDS (Previously RecordTrac)
            </h2>
            <p>
                The 2013 Code for America fellows created RecordTrac for the City of Oakland in response to public
                complaints that people did not know what happened after submitting FOIL requests and that the response
                time was too long. By making the process transparent, requesters could know when their requests were
                fulfilled.
                In 2014, the Department of Records and Information Services and the Department of Information Technology
                and Telecommunications began working with the open source code from the Oakland application to create
                additional features and functionality required to meet the FOIL needs of New York City agencies. The
                resulting FOIL portal is part of Mayor de Blasio's overall initiative for transparency in government.
                The
                initial beta version of OpenRecords was released in March 2015 for use with eight pilot agencies. The
                current version 2.1 was released in August 2017 and is used by 38 agencies, with more to be added on a
                regular basis. The DORIS development team rewrote all of the code to increase the stability and
                robustness of the application.

            </p>
            <hr>
            <h2 class="about-heading">Harvard Ash Center Bright Ideas Award 2017</h2>
            <div class="col-sm-5">&nbsp;</div>
            <div class="row-fluid">
                <div id="about-award-image-1" class="span2">
                    <img src="{{ url_for('static', filename='img/bright_idea_award_logo.jpg') }}"
                         alt="Bright Ideas Logo"
                         width="100" height="100"/></div>
            </div>
            <br />

            <p><em>“Bright Ideas is an initiative that recognizes creative and promising government programs and
                partnerships. The initiative is offered through the Innovations in Government Program, a program of the
                Ash Center for Democratic Governance and Innovation at Harvard Kennedy School. For more information,
                please visit <a href='http://innovationsaward.harvard.edu/BrightIdeas.cfm'>http://innovationsaward.harvard.edu/BrightIdeas.cfm</a></em>
            </p>
            <hr>
            <h2 class="about-heading">Center for Digital Government’s Best of NY Awards winner 2018 </h2>
            <div class="col-sm-5">&nbsp;</div>
            <div class="row-fluid">
                <div id="about-award-image-2" class="span2">
                    <img src="{{ url_for('static', filename='img/best_of_new_york_winner-2018.jpg') }}"
                         alt="Best of New York 2018 - Winner Logo"
                         height="100"/></div>
            </div>
            <br />

            <p><em>“Presented by e.Republic’s Center for Digital Government, in partnership with the state of New York,
                the Best of New York Awards recognize state and local government organizations for their standout
                contributions, best practices and innovations in information technology that improve citizen services
                and internal operations. For more information,
                please visit <a href='http://www.govtech.com/cdg/best-of-new-york/Best-of-New-York-Awards-2018---Winners-Announced.html'>http://www.govtech.com/cdg/best-of-new-york/Best-of-New-York-Awards-2018---Winners-Announced.htmlm</a></em>
            </p>
        </div>
    </div>
{% endblock %}

app/templates/main/contact.html
{% extends "base.html" %}

{% block title %}Technical Support{% endblock %}

{% block custom_css %}
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='styles/plugins/parsley.css') }}"/>
{% endblock %}

{% block content %}
    <div role="main">
        <h1 class="text-center">Technical Support</h1>
        <p align="center">Use this form only for technical support. Agency contact for other questions and information is
            available within the actual request.</p>
        <br/>
        <div>
            <form id="contact-info" action="{{ url_for('main.technical_support') }}" method="POST" role="form" data-parsley-focus="first">

                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

                <label for="name">Name</label>
                <input id="name" class="form-control" name="name" maxlength="32" type="text" aria-label="Name, required, 32 character limit">
                <p id="name-character-count" class="character-counter">32 characters remaining</p>
                <br>
                <label for="email" aria-label="Email">Email</label>
                <input id="email" class="form-control" name="email" maxlength="254" type="email" aria-label="Email, required, 254 character limit">
                <br>
                <label for="subject">Subject</label>
                <input id="subject" class="form-control" name="subject" maxlength="90" type="text" value="{{ error_id }}" aria-label="Subject, required, 90 character limit">
                <p id="subject-character-count" class="character-counter">90 characters remaining</p>
                <br>
                <label for="message">Message</label>
                <textarea id="message" name="message" rows="10" maxlength="5000" aria-label="Message, required, 5000 character limit"></textarea>
                <p id="message-character-count" class="character-counter">5000 characters remaining</p>

                <br>
                {{ form.recaptcha }}
                <input id="submit" name="submit" type="submit" value="Send" aria-label="Submit button">
            </form>
        </div>
    </div>
{% endblock %}

{% block custom_script %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/plugins/parsley.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/request/contact.js') }}"></script>
{% endblock %}

app/templates/main/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock title %}

{% block custom_css %}
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='styles/home.css') }}"/>
{% endblock %}
{% block content %}
    <div class="container col-sm-12">
        <div class="alert alert-info home-page-description">Don’t forget the census. Take a few minutes to help NYC get its fair share of
            federal funds. Go to <a href="https://my2020census.gov/">my2020census.gov</a> to complete the census.
        </div>
        <div class=" col-sm-8" role="main">
            <h1 class="home-page-header">Welcome to NYC Government’s home for filing Freedom of Information Law (FOIL)
                requests.
            </h1>
            <p class="home-page-description">On this site you can request records from every New York City agency by
                filing a Freedom of Information Law (FOIL)
                request. But, some government information is already available online and you wouldn’t need to go
                through the
                FOIL process. Check out these links to sites that host government reports and data. You may find what
                you are
                looking for without FOIL.
            </p>
            <p class="home-page-description">
                <strong>Government Reports and Data are available here</strong>
            </p>
            <ul class="nyc-gov-links home-page-description">
                <li>
                    <a href="http://nyc.gov/publications">NYC Government Publications Portal</a> Get copies of reports
                    and other publications issued by City agencies.
                </li>
                <li>
                    <a href="https://data.cityofnewyork.us/">NYC OpenData Portal</a> Discover open datasets for your
                    use.
                </li>
                <li>
                    <a href="http://www1.nyc.gov/">NYC.gov</a> The official website of the City of New York.
                </li>
                <li>
                    <a href="http://www1.nyc.gov/311/index.page">NYC 311</a> Get information about your neighborhood,
                    and check the status of existing requests.
                </li>
            </ul>
            <p class="home-page-description">Almost all City agencies also use this platform to respond to FOIL requests
                and publish records not covered by privacy
                and other protections.
            </p>
        </div>
        <div class="col-sm-4 well public-authorities" role="complementary">
            <h2 class="public-authorities-header">
                Local Public Authorities and Agencies not using OpenRecords
            </h2>
            <ul class="nyc-gov-links">
                <li>
                    <a class="non-portal-agency-link" href="http://www.nyc.gov/health">Department of Health and Mental Hygiene (DOHMH)</a>
                </li>
                <li>
                    <a class="non-portal-agency-link" href="http://www.nycedc.com">NYC Economic Development Corporation (NYEDC)</a>
                </li>
                <li>
                    <a class="non-portal-agency-link" href="http://www.nychealthandhospitals.org/">NYC Health and Hospitals Corporation (HHC)</a>
                </li>
                <li>
                    <a class="non-portal-agency-link" href="http://www.nyc.gov/nycha">New York City Housing Authority (NYCHA)</a>
                </li>
                <li>
                    <a class="non-portal-agency-link" href="http://www.snpnyc.org">Office of the Special Narcotics Prosecutor (SNP)</a>
                </li>
            </ul>
        </div>
        <div class="col-sm-12 request-record-button" role="navigation" aria-label="Search or request a record">
            <div class="col-sm-6">
                <a href="{{ url_for('request.view_all') }}">
                    <button class="btn btn-primary btn-lg btn-block request-record-button-size">Check for Similar
                        Requests
                    </button>
                </a>
            </div>
            <div class="col-sm-6">
                <a href="{{ url_for('request.new') }}">
                    <button class="btn btn-primary btn-lg btn-block request-record-button-size">Request a Record
                    </button>
                </a>
            </div>
        </div>
    </div>
{% endblock %} {% block custom_script %}
    <script type="text/javascript">
        "use strict";

        /* Redirect to OAuth callback if authorization location intended
         * (i.e. includes 'access_token=' after fragment identifier).
         * Also include 'next' url (or any other querystring parameters)
         * if present in the redirect uri.
         */
        if (window.location.hash.indexOf('access_token=') !== -1) {
            $('#login-processing-modal').modal("show");
            var url = window.location.origin +
                '/auth/authorize?' +
                window.location.hash.substring(1) // remove leading '#'
                +
                (window.location.search ? '&' + window.location.search.substring(1) : ''); // remove leading '?'
            $.ajax({
                url: url,
                type: 'GET',
                success: function (data) {
                    window.location = data['next']
                }
            });
        }
    </script>
{% endblock %}